/**
 * src/config/captureCriteria.js
 * Míster11 — Manual Canónico de Criterios de Captura
 *
 * Fichas binarias operativas con definición in situ (2 líneas),
 * reglas SÍ/NO, ejemplo de banda, botón y métricas alimentadas.
 */

export const CAPTURE_CRITERIA = [
  // ── REMATES Y GOLES ───────────────────────────────────────────────────────
  {
    id: 'shot_on_target',
    category: 'shots',
    nameEs: 'Tiro a Puerta',
    nameEn: 'Shot on Target',
    shortEs: 'Tiro que entra o habría entrado entre los tres palos sin intervención del portero o último defensa.',
    shortEn: 'Shot entering or that would have entered between the posts without goalkeeper/defender intervention.',
    binaryRuleEs: '¿El balón iba en dirección directa entre los palos y habría entrado sin mediar intervención? SÍ = Tiro a puerta.',
    binaryRuleEn: 'Was the ball going directly between the posts and would have entered without intervention? YES = Shot on target.',
    whenYesEs: 'Disparos dentro de los tres palos salvados por el portero, despejados sobre la línea por un defensor o que terminan en gol.',
    whenYesEn: 'Shots between posts saved by the keeper, cleared off the line by a defender, or converted into goals.',
    whenNoEs: 'Disparos que dan al poste y salen fuera, o remates desviados bloqueados por un defensa lejos de la línea.',
    whenNoEn: 'Shots hitting the woodwork and going out, or off-target shots blocked by a defender far from the line.',
    touchlineExampleEs: 'Delantero cruza remate raso, el portero mete la punta de la bota y desvía al córner.',
    touchlineExampleEn: 'Striker shoots low across goal, keeper touches with boot tip deflecting to corner.',
    buttonLabel: 'TIRO -> A puerta / Parada',
    feeds: ['Nota de rendimiento', 'Radar técnico', 'xG propio/rival', 'Exposición 2D', 'DAFO'],
  },
  {
    id: 'shot_off_target',
    category: 'shots',
    nameEs: 'Tiro Fuera / Desviado',
    nameEn: 'Shot Missed / Off Target',
    shortEs: 'Remate que no va en dirección a portería y sale fuera de los límites sin rozar los palos para gol.',
    shortEn: 'Attempt that is not directed towards the goal and goes out of bounds.',
    binaryRuleEs: '¿El balón iba hacia afuera de los tres palos? SÍ = Tiro fuera.',
    binaryRuleEn: 'Was the ball heading wide/over the three posts? YES = Shot off target.',
    whenYesEs: 'Cualquier disparo que cruce la línea de fondo por fuera o por encima del travesaño.',
    whenYesEn: 'Any shot crossing the endline wide or over the crossbar.',
    whenNoEs: 'Centros pasados que nadie remata y no buscan puerta.',
    whenNoEn: 'Overhit crosses that no one finishes and do not target the goal.',
    touchlineExampleEs: 'Volea desde la frontal que se marcha dos metros sobre el larguero.',
    touchlineExampleEn: 'Volley from outside the box that sails two meters over the crossbar.',
    buttonLabel: 'TIRO -> Fuera',
    feeds: ['Volumen de tiro', 'xG acumulado', 'DAFO eficacia'],
  },
  {
    id: 'shot_blocked',
    category: 'shots',
    nameEs: 'Tiro Bloqueado',
    nameEn: 'Blocked Shot',
    shortEs: 'Remate interceptado en trayectoria por un jugador de campo rival antes de llegar a puerta.',
    shortEn: 'Shot intercepted on its flight path by an opposing outfield defender.',
    binaryRuleEs: '¿El disparo impactó contra un rival que bloqueó su trayectoria? SÍ = Bloqueado.',
    binaryRuleEn: 'Did the shot hit an opponent blocking its trajectory? YES = Blocked.',
    whenYesEs: 'Defensas que se lanzan al suelo o rechazan con el cuerpo un remate del rival.',
    whenYesEn: 'Defenders throwing themselves to block or deflecting a shot with their body.',
    whenNoEs: 'Pases interceptados o despejes sin intención de remate.',
    whenNoEn: 'Intercepted passes or clearances with no shooting attempt.',
    touchlineExampleEs: 'Extremo recorta hacia dentro, dispara con fuerza y el central tapa el balón con las piernas.',
    touchlineExampleEn: 'Winger cuts inside, shoots hard and the center-back blocks with his legs.',
    buttonLabel: 'TIRO -> Bloqueado',
    feeds: ['xG acumulado', 'Densidad defensiva'],
  },
  {
    id: 'goal',
    category: 'shots',
    nameEs: 'Gol Consecutivo',
    nameEn: 'Goal',
    shortEs: 'El balón supera completamente la línea de meta reglamentaria.',
    shortEn: 'The ball completely crosses the legal goal line.',
    binaryRuleEs: '¿El balón cruzó por completo la línea de gol? SÍ = Gol.',
    binaryRuleEn: 'Did the ball cross the goal line completely? YES = Goal.',
    whenYesEs: 'Goles en jugada, penalti, falta directa, córner o autogol.',
    whenYesEn: 'Goals from open play, penalty, direct free kick, corner, or own goal.',
    whenNoEs: 'Goles anulados por fuera de juego o falta previa sancionada por el árbitro.',
    whenNoEn: 'Disallowed goals due to offside or preceding foul blown by referee.',
    touchlineExampleEs: 'Cabezazo picado al segundo palo que besa la red.',
    touchlineExampleEn: 'Downward header to far post that kisses the net.',
    buttonLabel: 'GOL / TIRO -> Gol',
    feeds: ['Marcador oficial', 'Nota (+1.5)', 'XP (+10)', 'xG conversión', 'DAFO'],
  },
  {
    id: 'assist',
    category: 'shots',
    nameEs: 'Asistencia de Gol',
    nameEn: 'Goal Assist',
    shortEs: 'Último pase voluntario directo que habilita al goleador para anotar.',
    shortEn: 'Final intentional pass directly enabling the scorer to convert.',
    binaryRuleEs: '¿Fue el último toque de un compañero antes de que el rematador anotara? SÍ = Asistencia.',
    binaryRuleEn: 'Was it the teammate’s last touch before the scorer converted? YES = Assist.',
    whenYesEs: 'Pase filtrado, centro raso o aéreo, o saque de esquina que termina inmediatamente en gol.',
    whenYesEn: 'Through ball, cross, or corner that immediately results in a goal.',
    whenNoEs: 'Balones rebotados involuntarios o penaltis provocados (salvo regla explícita).',
    whenNoEn: 'Involuntary ricochets or penalties drawn.',
    touchlineExampleEs: 'Pase al hueco que deja al delantero mano a mano frente al portero.',
    touchlineExampleEn: 'Through pass leaving the striker one-on-one with the goalkeeper.',
    buttonLabel: 'Chip Asistencia en ShotModal',
    feeds: ['Nota de rendimiento', 'Asistencias en informe', 'XP del jugador (+5)'],
  },
  {
    id: 'key_pass',
    category: 'shots',
    nameEs: 'Pase Clave',
    nameEn: 'Key Pass',
    shortEs: 'Último pase que culmina directamente en un remate a portería de un compañero sin terminar en gol.',
    shortEn: 'Last pass leading directly to a shot attempt by a teammate without scoring a goal.',
    binaryRuleEs: '¿El receptor remató a portería directamente gracias a este pase? SÍ = Pase Clave.',
    binaryRuleEn: 'Did the receiver take a shot directly thanks to this pass? YES = Key Pass.',
    whenYesEs: 'Pase filtrado, centro o pase atrás que genera un tiro a puerta o tiro fuera inmediato.',
    whenYesEn: 'Through ball, cross, or cutback directly producing an immediate shot attempt.',
    whenNoEs: 'Pases en zona de inicio o progresión tras los cuales el receptor da múltiples toques o regatea antes de tirar.',
    whenNoEn: 'Passes in build-up where the receiver takes multiple touches or dribbles before shooting.',
    touchlineExampleEs: 'Mediapunta filtra entre centrales y el extremo remata raso de primeras.',
    touchlineExampleEn: 'Playmaker slides ball through centerbacks and winger shoots first time.',
    buttonLabel: '⚡ Avanzado -> Pase Clave',
    feeds: ['Nota individual (+0.4)', 'Radar técnico'],
  },

  // ── ACCIONES DE PORTERÍA (GK 🧤) ─────────────────────────────────────────────────────────
  {
    id: 'save_normal',
    category: 'gk',
    nameEs: 'Parada Normal (GK)',
    nameEn: 'Normal Save (GK)',
    shortEs: 'Intervención de rutina o posicionamiento adecuado que detiene o desvía un tiro a puerta.',
    shortEn: 'Routine stop or proper positioning deflecting a shot on target.',
    binaryRuleEs: '¿El remate a puerta fue atajado sin una exigencia acrobática extrema? SÍ = Parada Normal.',
    binaryRuleEn: 'Was the shot on target stopped without extreme athletic heroics? YES = Normal Save.',
    whenYesEs: 'Tiros desde la frontal atrapados o despejes sin gran estirada de reflejos.',
    whenYesEn: 'Shots from outside gathered cleanly or deflected without desperate reach.',
    whenNoEs: 'Balones que iban fuera o centros que el portero descuelga sin tiro a puerta.',
    whenNoEn: 'Shots heading wide or crosses claimed without a shot on target.',
    touchlineExampleEs: 'Disparo centrado que el arquero embolsa contra el pecho.',
    touchlineExampleEn: 'Central shot that the keeper gathers securely against chest.',
    buttonLabel: 'TIRO RIVAL -> Parada -> Normal / HUD GK 🧤',
    feeds: ['Nota GK (1x)', 'XP (+2)', 'Exigencia GK', 'DAFO'],
  },
  {
    id: 'save_decisive',
    category: 'gk',
    nameEs: 'Parada Decisiva (GK)',
    nameEn: 'Decisive Save (GK)',
    shortEs: 'Intervención extraordinaria, mano a mano o estirada a bocajarro que evita un gol inminente (pondera x2).',
    shortEn: 'Extraordinary intervention, 1v1, or point-blank save preventing an imminent goal (counts x2).',
    binaryRuleEs: '¿La intervención evitó un gol cantado en clara desventaja? SÍ = Parada Decisiva.',
    binaryRuleEn: 'Did the stop deny an almost certain goal at clear disadvantage? YES = Decisive Save.',
    whenYesEs: 'Mano a mano ganado al delantero, estirada a la escuadra o parada a bocajarro en el área chica.',
    whenYesEn: 'Won 1v1 against striker, top-corner fingertips, or point-blank six-yard stop.',
    whenNoEs: 'Paradas cómodas o disparos con poca fuerza.',
    whenNoEn: 'Comfortable saves or weak shots.',
    touchlineExampleEs: 'Delantero remata solo a dos metros y el portero saca una mano milagrosa.',
    touchlineExampleEn: 'Striker shoots unmarked from 6 yards and keeper pulls off a miracle reflex hand.',
    buttonLabel: 'TIRO RIVAL -> Parada -> Decisiva',
    feeds: ['Nota GK (x2)', 'XP (+4)', 'Exigencia GK (x2)', 'DAFO Héroe'],
  },
  {
    id: 'penalty_save',
    category: 'gk',
    nameEs: 'Penalti Parado (GK)',
    nameEn: 'Penalty Saved (GK)',
    shortEs: 'Pena máxima detenida o desviada por el guardameta en tiempo reglamentario.',
    shortEn: 'Penalty kick stopped or deflected by the goalkeeper during regulation.',
    binaryRuleEs: '¿El portero tocó y detuvo o desvió el penalti rival? SÍ = Penalti Parado.',
    binaryRuleEn: 'Did the keeper touch and stop or divert the opponent penalty? YES = Penalty Saved.',
    whenYesEs: 'Cualquier penalti lanzado a puerta que el portero rechaza o atrapa.',
    whenYesEn: 'Any penalty on target blocked or caught by the keeper.',
    whenNoEs: 'Penalti que el lanzador rival tira directamente fuera sin que el arquero lo toque.',
    whenNoEn: 'Penalty sent wide/high by shooter without keeper contact.',
    touchlineExampleEs: 'El portero adivina el lado derecho y despeja el penalti a media altura.',
    touchlineExampleEn: 'Keeper guesses right corner and pushes away the mid-height penalty.',
    buttonLabel: 'HUD GK 🧤 -> Penalti',
    feeds: ['Nota GK (+2.0)', 'XP (+10)', 'DAFO'],
  },
  {
    id: 'gk_claim',
    category: 'gk',
    nameEs: 'Salida / Balón Aéreo (GK)',
    nameEn: 'Claim / Aerial Ball (GK)',
    shortEs: 'Intervención exitosa del portero saliendo de su arco para atrapar o despejar de puños un centro.',
    shortEn: 'Successful intervention by keeper coming off line to catch or punch a cross.',
    binaryRuleEs: '¿El arquero salió de su área de confort para interceptar un envío aéreo? SÍ = Salida/Rechace.',
    binaryRuleEn: 'Did the keeper leave their line to intercept an aerial cross? YES = Claim.',
    whenYesEs: 'Córners descolgados en el área de meta o salidas decididas cortando balones aéreos.',
    whenYesEn: 'Corners caught in traffic or brave punches clearing aerial service.',
    whenNoEs: 'Balones que llegan rodando mansamente al área chica.',
    whenNoEn: 'Slow rolling passes into the six-yard box.',
    touchlineExampleEs: 'Salida con autoridad en un córner cerrado despejando a dos puños.',
    touchlineExampleEn: 'Authoritative jump on an in-swinging corner punching clear with two fists.',
    buttonLabel: 'HUD GK 🧤 -> Salida',
    feeds: ['Nota GK (+0.3)', 'Seguridad defensiva'],
  },
  {
    id: 'gk_error_goal',
    category: 'gk',
    nameEs: 'Error Que Causa Gol (GK)',
    nameEn: 'Error Leading to Goal (GK)',
    shortEs: 'Fallo técnico flagrante o pérdida directa del portero que propicia inmediatamente un gol rival.',
    shortEn: 'Blatant technical error or giveaway by keeper immediately yielding an opponent goal.',
    binaryRuleEs: '¿El gol rival se originó por una pifia técnica evidente del portero? SÍ = Error.',
    binaryRuleEn: 'Did opponent goal stem from an evident keeper blunder? YES = Error to goal.',
    whenYesEs: 'Balón que se le escurre entre las manos, pase al rival en salida o mala salida a destiempo.',
    whenYesEn: 'Ball slipping through gloves, bad pass out directly to striker, or mistimed rush.',
    whenNoEs: 'Mano a mano donde el delantero define bien sin error del arquero.',
    whenNoEn: '1v1 where striker finishes cleanly with no goalkeeping blunder.',
    touchlineExampleEs: 'El portero intenta controlar con el pie, se le escapa el balón y el rival anota a placer.',
    touchlineExampleEn: 'Keeper tries to control with foot, loses ball and rival taps into open net.',
    buttonLabel: 'HUD GK 🧤 -> Error',
    feeds: ['Nota GK (-1.5)', 'DAFO debilidades'],
  },

  // ── DEFENSA Y DUELOS ──────────────────────────────────────────────────────
  {
    id: 'recovery',
    category: 'defense',
    nameEs: 'Recuperación',
    nameEn: 'Ball Recovery',
    shortEs: 'Acción exitosa en la que el equipo recupera la posesión limpia del balón.',
    shortEn: 'Successful action winning back clean possession for the team.',
    binaryRuleEs: '¿El balón pasó de control rival a posesión estable de nuestro equipo? SÍ = Recuperación.',
    binaryRuleEn: 'Did ball switch from rival control to stable possession for us? YES = Recovery.',
    whenYesEs: 'Intercepciones de pase, anticipaciones limpias o robos tras presión.',
    whenYesEn: 'Pass interceptions, clean anticipations, or tackles winning possession.',
    whenNoEs: 'Despejes que vuelven a caer en los pies del rival.',
    whenNoEn: 'Clearances that fall right back to opponent boots.',
    touchlineExampleEs: 'Mediocentro corta la línea de pase rival y conecta inmediatamente con el mediapunta.',
    touchlineExampleEn: 'Midfielder cuts rival passing lane and immediately feeds the playmaker.',
    buttonLabel: 'HUD -> RECUPERACIÓN',
    feeds: ['Nota (+0.25)', 'Radar posesión', 'Momentum', 'DAFO'],
  },
  {
    id: 'duel_won',
    category: 'defense',
    nameEs: 'Duelo Ganado',
    nameEn: 'Duel Won',
    shortEs: 'Disputa individual 1 contra 1 (terrestre o aérea) donde nuestro jugador se impone con el balón.',
    shortEn: 'Individual 1v1 contest (ground or aerial) where our player prevails with ball.',
    binaryRuleEs: '¿Hubo pugna directa entre dos jugadores y el nuestro salió victorioso? SÍ = Duelo Ganado.',
    binaryRuleEn: 'Was there a direct contest between 2 players and ours came out on top? YES = Duel Won.',
    whenYesEs: 'Entradas limpias donde el rival pierde el balón, regates completados o cabezazos ganados en salto.',
    whenYesEn: 'Clean tackles taking ball off rival, successful dribbles past defender, or aerial headers won.',
    whenNoEs: 'Recogida de balones sueltos sin oposición directa de un rival.',
    whenNoEn: 'Picking up loose balls with no opponent challenging.',
    touchlineExampleEs: 'Lateral mete cuerpo hombro con hombro y le arrebata limpiamente el balón al extremo.',
    touchlineExampleEn: 'Fullback uses body shoulder-to-shoulder cleanly stripping the winger.',
    buttonLabel: 'HUD -> DUELO GANADO',
    feeds: ['Nota (+0.25)', 'Radar duelos', 'DAFO superioridad'],
  },
  {
    id: 'duel_lost',
    category: 'defense',
    nameEs: 'Duelo Perdido',
    nameEn: 'Duel Lost',
    shortEs: 'Pugna directa 1v1 donde el rival se impone, supera la marca o gana el salto.',
    shortEn: 'Direct 1v1 contest where the opponent prevails, bypasses marker, or wins header.',
    binaryRuleEs: '¿El rival superó directamente a nuestro jugador en el 1 contra 1? SÍ = Duelo Perdido.',
    binaryRuleEn: 'Did the rival directly beat our player in a 1-on-1 contest? YES = Duel Lost.',
    whenYesEs: 'Defensa que es regateado, delantero que pierde el balón al chocar o salto aéreo perdido.',
    whenYesEn: 'Defender getting dribbled past, attacker losing ball on tackle, or lost aerial duel.',
    whenNoEs: 'Pases imprecisos sin disputa física directa.',
    whenNoEn: 'Inaccurate passes without direct physical challenge.',
    touchlineExampleEs: 'El extremo rival supera en carrera y velocidad a nuestro defensa en la banda.',
    touchlineExampleEn: 'Rival winger beats our fullback on pace and acceleration down the flank.',
    buttonLabel: 'HUD Avanzado -> Duelo Perdido',
    feeds: ['Radar % eficacia duelos', 'DAFO debilidad'],
  },
  {
    id: 'ball_loss',
    category: 'defense',
    nameEs: 'Pérdida / Turnover',
    nameEn: 'Ball Loss / Turnover',
    shortEs: 'Pérdida involuntaria de la posesión bajo presión rival o fallo no forzado en conducción.',
    shortEn: 'Involuntary loss of possession under pressure or unforced error while carrying ball.',
    binaryRuleEs: '¿Nuestro equipo tenía posesión controlada y la entregó al rival? SÍ = Pérdida.',
    binaryRuleEn: 'Did our team have controlled possession and give it to rival? YES = Turnover.',
    whenYesEs: 'Despojo del balón al intentar gambetear o mal control que aprovecha el rival.',
    whenYesEn: 'Dispossession while dribbling or heavy touch seized by opponent.',
    whenNoEs: 'Tiros a puerta que el portero rival atrapa.',
    whenNoEn: 'Shots on target caught by opposing goalkeeper.',
    touchlineExampleEs: 'Pérdida en salida defensiva al intentar salir jugando entre dos atacantes.',
    touchlineExampleEn: 'Turnover in defensive third trying to play out between two pressing forwards.',
    buttonLabel: 'HUD Avanzado -> Pérdida',
    feeds: ['DAFO pérdidas críticas', 'Transiciones concedidas'],
  },

  // ── DISCIPLINA Y FALTAS ───────────────────────────────────────────────────
  {
    id: 'foul_against',
    category: 'fouls',
    nameEs: 'Falta Cometida',
    nameEn: 'Foul Conceded',
    shortEs: 'Infracción reglamentaria cometida por un jugador de nuestro equipo que detiene el juego.',
    shortEn: 'Infraction committed by our team player whistled by the referee.',
    binaryRuleEs: '¿El árbitro señaló infracción contra nuestro equipo? SÍ = Falta Cometida.',
    binaryRuleEn: 'Did referee blow foul against our team? YES = Foul Conceded.',
    whenYesEs: 'Entradas a destiempo, empujones, manos o juego peligroso sancionado con tiro libre.',
    whenYesEn: 'Late tackles, pushes, handballs, or dangerous play awarded as free kicks.',
    whenNoEs: 'Ley de la ventaja donde no se pita nada.',
    whenNoEn: 'Advantage played without a whistle.',
    touchlineExampleEs: 'Agarrón continuado de la camiseta para frenar un contragolpe rival.',
    touchlineExampleEn: 'Shirt pull to halt an opposing fast counter-attack.',
    buttonLabel: 'HUD / Equipo -> FALTA CONTRA',
    feeds: ['Nota (-0.2)', 'Radar faltas', 'DAFO balón parado concedido'],
  },
  {
    id: 'foul_favor',
    category: 'fouls',
    nameEs: 'Falta a Favor',
    nameEn: 'Foul Won',
    shortEs: 'Infracción recibida por nuestro equipo que nos concede tiro libre o penalti.',
    shortEn: 'Infraction suffered by our team granting us a free kick or penalty.',
    binaryRuleEs: '¿El árbitro pitó falta a favor de nuestro equipo? SÍ = Falta a Favor.',
    binaryRuleEn: 'Did referee whistle a foul in our favor? YES = Foul Won.',
    whenYesEs: 'Derribos a nuestros delanteros o faltas tácticas recibidas.',
    whenYesEn: 'Trips on our forwards or tactical fouls suffered.',
    whenNoEs: 'Fueras de juego del rival (son infracciones técnicas, no faltas).',
    whenNoEn: 'Opponent offsides (technical infractions, not fouls).',
    touchlineExampleEs: 'Zancadilla al extremo cuando se escapaba en el pico del área.',
    touchlineExampleEn: 'Trip on winger as he burst past at the edge of the box.',
    buttonLabel: 'HUD / Equipo -> FALTA FAVOR',
    feeds: ['Generación balón parado', 'Momentum'],
  },
  {
    id: 'card_yellow',
    category: 'fouls',
    nameEs: 'Tarjeta Amarilla',
    nameEn: 'Yellow Card',
    shortEs: 'Amonestación disciplinaria formal mostrada por el árbitro con cartulina amarilla.',
    shortEn: 'Formal disciplinary caution displayed by referee showing yellow card.',
    binaryRuleEs: '¿El árbitro amonestó con tarjeta amarilla? SÍ = Tarjeta Amarilla.',
    binaryRuleEn: 'Did referee show a yellow card? YES = Yellow Card.',
    whenYesEs: 'Faltas reiteradas, entradas bruscas, pérdidas deliberadas de tiempo o protestas.',
    whenYesEn: 'Reckless tackles, persistent fouling, time wasting, or dissent.',
    whenNoEs: 'Advertencias verbales del colegiado sin mostrar tarjeta.',
    whenNoEn: 'Verbal warnings from referee without card.',
    touchlineExampleEs: 'Derribo por detrás sin opción de balón en el centro del campo.',
    touchlineExampleEn: 'Clipping from behind with no play on the ball in midfield.',
    buttonLabel: 'Equipo -> AMARILLA',
    feeds: ['Nota (-0.5)', 'XP (-2)', 'Radar disciplina', 'Acta'],
  },
  {
    id: 'card_red',
    category: 'fouls',
    nameEs: 'Tarjeta Roja',
    nameEn: 'Red Card',
    shortEs: 'Expulsión directa o por doble amonestación de un jugador del terreno de juego.',
    shortEn: 'Direct red card or second yellow resulting in player ejection.',
    binaryRuleEs: '¿El árbitro expulsó al jugador del campo? SÍ = Tarjeta Roja.',
    binaryRuleEn: 'Did referee eject player from the pitch? YES = Red Card.',
    whenYesEs: 'Roja directa por agresión/falta como último hombre o segunda amarilla.',
    whenYesEn: 'Straight red for violent conduct/last defender or second yellow card.',
    whenNoEs: 'Amonestaciones al banquillo o técnicos salvo que se auditen jugadores.',
    whenNoEn: 'Bench staff cautions unless logging squad events.',
    touchlineExampleEs: 'Entrada con tacos por delante a la altura de la rodilla.',
    touchlineExampleEn: 'High stud tackle at knee height.',
    buttonLabel: 'Equipo -> ROJA',
    feeds: ['Nota (-1.5)', 'XP (-5)', 'Radar disciplina', 'Alineación activa', 'Acta'],
  },

  // ── BALÓN PARADO Y FUERA DE JUEGO ─────────────────────────────────────────
  {
    id: 'corner',
    category: 'set_pieces',
    nameEs: 'Saque de Esquina (Córner)',
    nameEn: 'Corner Kick',
    shortEs: 'El balón sale por la línea de fondo impulsado por el rival / por nosotros.',
    shortEn: 'Ball goes over endline last touched by defending team.',
    binaryRuleEs: '¿El juego se reanuda con un saque desde la esquina? SÍ = Córner.',
    binaryRuleEn: 'Does play restart from the corner arc? YES = Corner Kick.',
    whenYesEs: 'Saques de esquina a favor (equipo ataca) o en contra (equipo defiende).',
    whenYesEn: 'Corner kicks in favor (attacking) or against (defending).',
    whenNoEs: 'Saques de banda o saques de puerta ordinarios.',
    whenNoEn: 'Throw-ins or goal kicks.',
    touchlineExampleEs: 'El portero despeja a mano cambiada por encima del travesaño a córner.',
    touchlineExampleEn: 'Keeper tips over crossbar with top hand conceding corner kick.',
    buttonLabel: 'Equipo -> CÓRNER FAVOR / CONTRA',
    feeds: ['Radar córners', 'Peligro balón parado', 'DAFO'],
  },
  {
    id: 'offside',
    category: 'set_pieces',
    nameEs: 'Fuera de Juego (Offside)',
    nameEn: 'Offside',
    shortEs: 'Posición antirreglamentaria sancionada por el asistente levantando el banderín.',
    shortEn: 'Offside position penalized by assistant referee raising the flag.',
    binaryRuleEs: '¿El árbitro pitó posición adelantada? SÍ = Fuera de juego.',
    binaryRuleEn: 'Did referee blow for offside? YES = Offside.',
    whenYesEs: 'Tanto fueras de juego cometidos por nuestros delanteros como provocados a rivales.',
    whenYesEn: 'Both offsides committed by our forwards and offside traps sprung on rivals.',
    whenNoEs: 'Jugadas donde el juez de línea no levanta el banderín y el juego sigue.',
    whenNoEn: 'Plays where the flag stays down and play continues.',
    touchlineExampleEs: 'Pase en profundidad donde el delantero arrancó medio metro por delante del central.',
    touchlineExampleEn: 'Through ball where the forward started half a yard ahead of the last defender.',
    buttonLabel: 'Equipo -> OFFSIDE PROPIO / RIVAL',
    feeds: ['Radar offsides', 'Línea defensiva', 'DAFO'],
  },

  // ── EVENTOS SIN ATRIBUIR ──────────────────────────────────────────────────
  {
    id: 'unattributed_event',
    category: 'special',
    nameEs: 'Evento Sin Atribuir',
    nameEn: 'Unattributed Event',
    shortEs: 'Cualquier acción colectiva registrada a nivel de equipo sin identificar al jugador individual.',
    shortEn: 'Any collective action logged at team level without identifying individual player.',
    binaryRuleEs: '¿Se registró el evento sin seleccionar un dorsal específico? SÍ = Sin Atribuir.',
    binaryRuleEn: 'Was the event logged without picking a specific jersey/player? YES = Unattributed.',
    whenYesEs: 'Faltas en banda rápida, duelos en barullos o tiros rápidos sin tiempo de asignar.',
    whenYesEn: 'Quick fouls, scramble duels, or hurried shots without time to tag player.',
    whenNoEs: 'Eventos donde se seleccionó un jugador del carrusel o HUD individual.',
    whenNoEn: 'Events where a player was selected from carousel or individual HUD.',
    touchlineExampleEs: 'Barullo en el medio, falta a favor pitada rápido; se pulsa Falta Favor sin dorsal.',
    touchlineExampleEn: 'Midfield scramble, quick foul awarded; coach taps Foul Won without dorsal.',
    buttonLabel: 'Panel de Equipo / Chip "Sin atribuir"',
    feeds: ['Totales de equipo', 'Momentum', 'Exposición 2D', 'DAFO (NO contamina notas individuales ni XP)'],
  },
];

export const CRITERIA_CATEGORIES = [
  { id: 'all', labelEs: 'Todos', labelEn: 'All' },
  { id: 'shots', labelEs: '⚽ Remates y Goles', labelEn: '⚽ Shots & Goals' },
  { id: 'gk', labelEs: '🧤 Portería', labelEn: '🧤 Goalkeeping' },
  { id: 'defense', labelEs: '🛡️ Defensa y Duelos', labelEn: '🛡️ Defense & Duels' },
  { id: 'fouls', labelEs: '⚡ Faltas y Disciplina', labelEn: '⚡ Fouls & Discipline' },
  { id: 'set_pieces', labelEs: '🚩 Balón Parado', labelEn: '🚩 Set Pieces' },
  { id: 'special', labelEs: '🔘 Sin Atribuir', labelEn: '🔘 Unattributed' },
];

export const CAPTURE_CRITERIA_MAP = Object.fromEntries(
  CAPTURE_CRITERIA.map(c => [c.id, c])
);

// Permitir acceso directo por ID: CAPTURE_CRITERIA['shot_on_target']
CAPTURE_CRITERIA.forEach(c => {
  if (c && c.id) {
    CAPTURE_CRITERIA[c.id] = c;
  }
});
