export const PREDEFINED_FORMATIONS = {
  '4-3-3': [
    { pos: 'POR', top: '50%', left: '10%' },
    { pos: 'LTI', top: '16%', left: '28%' },
    { pos: 'DEF', top: '38%', left: '24%' },
    { pos: 'DEF', top: '62%', left: '24%' },
    { pos: 'LTD', top: '84%', left: '28%' },
    { pos: 'MCD', top: '50%', left: '46%' },
    { pos: 'MC', top: '28%', left: '60%' },
    { pos: 'MC', top: '72%', left: '60%' },
    { pos: 'EXT', top: '18%', left: '80%' },
    { pos: 'DEL', top: '50%', left: '88%' },
    { pos: 'EXT', top: '82%', left: '80%' }
  ],
  '4-4-2': [
    { pos: 'POR', top: '50%', left: '10%' },
    { pos: 'LTI', top: '16%', left: '28%' },
    { pos: 'DEF', top: '38%', left: '24%' },
    { pos: 'DEF', top: '62%', left: '24%' },
    { pos: 'LTD', top: '84%', left: '28%' },
    { pos: 'MI', top: '18%', left: '56%' },
    { pos: 'MC', top: '38%', left: '52%' },
    { pos: 'MC', top: '62%', left: '52%' },
    { pos: 'MD', top: '82%', left: '56%' },
    { pos: 'DEL', top: '38%', left: '84%' },
    { pos: 'DEL', top: '62%', left: '84%' }
  ],
  '4-4-2 (diamante)': [
    { pos: 'POR', top: '50%', left: '10%' },
    { pos: 'LTI', top: '16%', left: '28%' },
    { pos: 'DEF', top: '38%', left: '24%' },
    { pos: 'DEF', top: '62%', left: '24%' },
    { pos: 'LTD', top: '84%', left: '28%' },
    { pos: 'MCD', top: '50%', left: '44%' },
    { pos: 'MC', top: '26%', left: '58%' },
    { pos: 'MC', top: '74%', left: '58%' },
    { pos: 'MCO', top: '50%', left: '70%' },
    { pos: 'DEL', top: '38%', left: '86%' },
    { pos: 'DEL', top: '62%', left: '86%' }
  ],
  '3-4-3': [
    { pos: 'POR', top: '50%', left: '10%' },
    { pos: 'DEF', top: '26%', left: '25%' },
    { pos: 'DEF', top: '50%', left: '22%' },
    { pos: 'DEF', top: '74%', left: '25%' },
    { pos: 'MI', top: '16%', left: '52%' },
    { pos: 'MC', top: '38%', left: '48%' },
    { pos: 'MC', top: '62%', left: '48%' },
    { pos: 'MD', top: '84%', left: '52%' },
    { pos: 'EXT', top: '18%', left: '80%' },
    { pos: 'DEL', top: '50%', left: '86%' },
    { pos: 'EXT', top: '82%', left: '80%' }
  ],
  '5-4-1': [
    { pos: 'POR', top: '50%', left: '10%' },
    { pos: 'LTI', top: '15%', left: '28%' },
    { pos: 'DEF', top: '32%', left: '24%' },
    { pos: 'DEF', top: '50%', left: '21%' },
    { pos: 'DEF', top: '68%', left: '24%' },
    { pos: 'LTD', top: '85%', left: '28%' },
    { pos: 'MI', top: '20%', left: '56%' },
    { pos: 'MC', top: '40%', left: '50%' },
    { pos: 'MC', top: '60%', left: '50%' },
    { pos: 'MD', top: '80%', left: '56%' },
    { pos: 'DEL', top: '50%', left: '85%' }
  ],
  '4-1-4-1': [
    { pos: 'POR', top: '50%', left: '10%' },
    { pos: 'LTI', top: '16%', left: '28%' },
    { pos: 'DEF', top: '38%', left: '24%' },
    { pos: 'DEF', top: '62%', left: '24%' },
    { pos: 'LTD', top: '84%', left: '28%' },
    { pos: 'MCD', top: '50%', left: '44%' },
    { pos: 'MI', top: '18%', left: '64%' },
    { pos: 'MC', top: '38%', left: '60%' },
    { pos: 'MC', top: '62%', left: '60%' },
    { pos: 'MD', top: '82%', left: '64%' },
    { pos: 'DEL', top: '50%', left: '86%' }
  ],
  '4-2-3-1': [
    { pos: 'POR', top: '50%', left: '10%' },
    { pos: 'LTI', top: '16%', left: '28%' },
    { pos: 'DEF', top: '38%', left: '24%' },
    { pos: 'DEF', top: '62%', left: '24%' },
    { pos: 'LTD', top: '84%', left: '28%' },
    { pos: 'MCD', top: '38%', left: '46%' },
    { pos: 'MCD', top: '62%', left: '46%' },
    { pos: 'EXT', top: '18%', left: '70%' },
    { pos: 'MCO', top: '50%', left: '68%' },
    { pos: 'EXT', top: '82%', left: '70%' },
    { pos: 'DEL', top: '50%', left: '88%' }
  ],
  '3-5-2': [
    { pos: 'POR', top: '50%', left: '10%' },
    { pos: 'DEF', top: '26%', left: '25%' },
    { pos: 'DEF', top: '50%', left: '22%' },
    { pos: 'DEF', top: '74%', left: '25%' },
    { pos: 'MI', top: '16%', left: '50%' },
    { pos: 'MC', top: '34%', left: '54%' },
    { pos: 'MCD', top: '50%', left: '46%' },
    { pos: 'MC', top: '66%', left: '54%' },
    { pos: 'MD', top: '84%', left: '50%' },
    { pos: 'DEL', top: '38%', left: '84%' },
    { pos: 'DEL', top: '62%', left: '84%' }
  ],
  '5-3-2': [
    { pos: 'POR', top: '50%', left: '10%' },
    { pos: 'LTI', top: '15%', left: '28%' },
    { pos: 'DEF', top: '32%', left: '24%' },
    { pos: 'DEF', top: '50%', left: '21%' },
    { pos: 'DEF', top: '68%', left: '24%' },
    { pos: 'LTD', top: '85%', left: '28%' },
    { pos: 'MC', top: '28%', left: '54%' },
    { pos: 'MCD', top: '50%', left: '46%' },
    { pos: 'MC', top: '72%', left: '54%' },
    { pos: 'DEL', top: '38%', left: '85%' },
    { pos: 'DEL', top: '62%', left: '85%' }
  ],
  '4-5-1': [
    { pos: 'POR', top: '50%', left: '10%' },
    { pos: 'LTI', top: '16%', left: '28%' },
    { pos: 'DEF', top: '38%', left: '24%' },
    { pos: 'DEF', top: '62%', left: '24%' },
    { pos: 'LTD', top: '84%', left: '28%' },
    { pos: 'MI', top: '18%', left: '58%' },
    { pos: 'MC', top: '38%', left: '54%' },
    { pos: 'MCD', top: '50%', left: '46%' },
    { pos: 'MC', top: '62%', left: '54%' },
    { pos: 'MD', top: '82%', left: '58%' },
    { pos: 'DEL', top: '50%', left: '85%' }
  ]
};
