export const PREDEFINED_FORMATIONS = {
  '4-3-3': [
    { pos: 'POR', top: '50%', left: '10%' },
    { pos: 'LTD', top: '85%', left: '30%' },
    { pos: 'DEF', top: '65%', left: '25%' },
    { pos: 'DEF', top: '35%', left: '25%' },
    { pos: 'LTI', top: '15%', left: '30%' },
    { pos: 'MCD', top: '50%', left: '50%' },
    { pos: 'MC', top: '75%', left: '60%' },
    { pos: 'MC', top: '25%', left: '60%' },
    { pos: 'EXT', top: '85%', left: '85%' },
    { pos: 'DEL', top: '50%', left: '90%' },
    { pos: 'EXT', top: '15%', left: '85%' }
  ],
  '4-4-2': [
    { pos: 'POR', top: '50%', left: '10%' },
    { pos: 'LTD', top: '85%', left: '30%' },
    { pos: 'DEF', top: '65%', left: '25%' },
    { pos: 'DEF', top: '35%', left: '25%' },
    { pos: 'LTI', top: '15%', left: '30%' },
    { pos: 'MD', top: '85%', left: '60%' },
    { pos: 'MC', top: '65%', left: '55%' },
    { pos: 'MC', top: '35%', left: '55%' },
    { pos: 'MI', top: '15%', left: '60%' },
    { pos: 'DEL', top: '65%', left: '85%' },
    { pos: 'DEL', top: '35%', left: '85%' }
  ],
  '4-4-2 (diamante)': [
    { pos: 'POR', top: '50%', left: '10%' },
    { pos: 'LTD', top: '85%', left: '30%' },
    { pos: 'DEF', top: '65%', left: '25%' },
    { pos: 'DEF', top: '35%', left: '25%' },
    { pos: 'LTI', top: '15%', left: '30%' },
    { pos: 'MCD', top: '50%', left: '48%' },
    { pos: 'MC', top: '75%', left: '60%' },
    { pos: 'MC', top: '25%', left: '60%' },
    { pos: 'MCO', top: '50%', left: '72%' },
    { pos: 'DEL', top: '65%', left: '85%' },
    { pos: 'DEL', top: '35%', left: '85%' }
  ],
  '3-4-3': [
    { pos: 'POR', top: '50%', left: '10%' },
    { pos: 'DEF', top: '70%', left: '25%' },
    { pos: 'DEF', top: '50%', left: '22%' },
    { pos: 'DEF', top: '30%', left: '25%' },
    { pos: 'MD', top: '85%', left: '55%' },
    { pos: 'MC', top: '60%', left: '50%' },
    { pos: 'MC', top: '40%', left: '50%' },
    { pos: 'MI', top: '15%', left: '55%' },
    { pos: 'EXT', top: '80%', left: '80%' },
    { pos: 'DEL', top: '50%', left: '85%' },
    { pos: 'EXT', top: '20%', left: '80%' }
  ],
  '5-4-1': [
    { pos: 'POR', top: '50%', left: '10%' },
    { pos: 'LTD', top: '85%', left: '28%' },
    { pos: 'DEF', top: '65%', left: '25%' },
    { pos: 'DEF', top: '50%', left: '22%' },
    { pos: 'DEF', top: '35%', left: '25%' },
    { pos: 'LTI', top: '15%', left: '28%' },
    { pos: 'MD', top: '80%', left: '55%' },
    { pos: 'MC', top: '60%', left: '50%' },
    { pos: 'MC', top: '40%', left: '50%' },
    { pos: 'MI', top: '20%', left: '55%' },
    { pos: 'DEL', top: '50%', left: '85%' }
  ],
  '4-1-4-1': [
    { pos: 'POR', top: '50%', left: '10%' },
    { pos: 'LTD', top: '85%', left: '30%' },
    { pos: 'DEF', top: '65%', left: '25%' },
    { pos: 'DEF', top: '35%', left: '25%' },
    { pos: 'LTI', top: '15%', left: '30%' },
    { pos: 'MCD', top: '50%', left: '45%' },
    { pos: 'MD', top: '80%', left: '65%' },
    { pos: 'MC', top: '60%', left: '60%' },
    { pos: 'MC', top: '40%', left: '60%' },
    { pos: 'MI', top: '20%', left: '65%' },
    { pos: 'DEL', top: '50%', left: '85%' }
  ],
  '4-2-3-1': [
    { pos: 'POR', top: '50%', left: '10%' },
    { pos: 'LTD', top: '85%', left: '30%' },
    { pos: 'DEF', top: '65%', left: '25%' },
    { pos: 'DEF', top: '35%', left: '25%' },
    { pos: 'LTI', top: '15%', left: '30%' },
    { pos: 'MCD', top: '62%', left: '48%' },
    { pos: 'MCD', top: '38%', left: '48%' },
    { pos: 'EXT', top: '80%', left: '72%' },
    { pos: 'MCO', top: '50%', left: '72%' },
    { pos: 'EXT', top: '20%', left: '72%' },
    { pos: 'DEL', top: '50%', left: '88%' }
  ],
  '3-5-2': [
    { pos: 'POR', top: '50%', left: '10%' },
    { pos: 'DEF', top: '70%', left: '25%' },
    { pos: 'DEF', top: '50%', left: '22%' },
    { pos: 'DEF', top: '30%', left: '25%' },
    { pos: 'MD', top: '85%', left: '50%' },
    { pos: 'MC', top: '65%', left: '55%' },
    { pos: 'MC', top: '50%', left: '58%' },
    { pos: 'MC', top: '35%', left: '55%' },
    { pos: 'MI', top: '15%', left: '50%' },
    { pos: 'DEL', top: '65%', left: '85%' },
    { pos: 'DEL', top: '35%', left: '85%' }
  ],
  '5-3-2': [
    { pos: 'POR', top: '50%', left: '10%' },
    { pos: 'LTD', top: '85%', left: '28%' },
    { pos: 'DEF', top: '65%', left: '25%' },
    { pos: 'DEF', top: '50%', left: '22%' },
    { pos: 'DEF', top: '35%', left: '25%' },
    { pos: 'LTI', top: '15%', left: '28%' },
    { pos: 'MC', top: '70%', left: '55%' },
    { pos: 'MCD', top: '50%', left: '48%' },
    { pos: 'MC', top: '30%', left: '55%' },
    { pos: 'DEL', top: '62%', left: '85%' },
    { pos: 'DEL', top: '38%', left: '85%' }
  ],
  '4-5-1': [
    { pos: 'POR', top: '50%', left: '10%' },
    { pos: 'LTD', top: '85%', left: '30%' },
    { pos: 'DEF', top: '65%', left: '25%' },
    { pos: 'DEF', top: '35%', left: '25%' },
    { pos: 'LTI', top: '15%', left: '30%' },
    { pos: 'MD', top: '82%', left: '60%' },
    { pos: 'MC', top: '62%', left: '55%' },
    { pos: 'MCD', top: '50%', left: '50%' },
    { pos: 'MC', top: '38%', left: '55%' },
    { pos: 'MI', top: '18%', left: '60%' },
    { pos: 'DEL', top: '50%', left: '85%' }
  ]
};
